Check and prevent duplicate bumps

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -33,6 +33,10 @@ jobs:
       - uses: actions/checkout@v2
       - uses: dawidd6/action-git-user-config@v1
 
+      - name: Check if head is already a bump
+        run: |
+          [[ "${{ github.event.head_commit.message }}" =~ "Bump version to" ]] && echo "::error::Duplicate bumps are not allowed" && exit 1
+
       - name: Bump version
         run: |
           VERSION=$(make version bump=${{ github.event.inputs.version }} --silent)
